#if !canImport(ObjectiveC)
  import XCTest

  extension MissiveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MissiveTests = [
      ("testCompiles", testCompiles)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(MissiveTests.__allTests__MissiveTests)
    ]
  }
#endif
