#if !canImport(ObjectiveC)
  import XCTest

  extension ChangeloggerExecutableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChangeloggerExecutableTests = [
      ("testInitNoArguments", testInitNoArguments),
      ("testInitWithArguments", testInitWithArguments),
      ("testMarkdownNoArguments", testMarkdownNoArguments),
      ("testRunNoArguments", testRunNoArguments)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(ChangeloggerExecutableTests.__allTests__ChangeloggerExecutableTests)
    ]
  }
#endif
