#if !canImport(ObjectiveC)
  import XCTest

  extension ChangelogTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChangelogTests = [
      ("testChangelogFilePaths", testChangelogFilePaths),
      ("testCreateEmptyChangelog", testCreateEmptyChangelog),
      ("testCreateMarkdown", testCreateMarkdown),
      ("testCreateNotEmptyChangelog", testCreateNotEmptyChangelog),
      ("testReadNotEmptyChangelog", testReadNotEmptyChangelog),
      ("testSquashUnreleasedEntries", testSquashUnreleasedEntries),
      ("testUpdateChangelogFile", testUpdateChangelogFile),
      ("testUpdateChangelogStruct", testUpdateChangelogStruct),
      ("testwriteChangelogYAML", testwriteChangelogYAML),
      ("testWriteMarkdown", testWriteMarkdown)
    ]
  }

  extension CommitEntryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommitEntryTests = [
      ("testCommitDefaultPathEmptyEntryNoError", testCommitDefaultPathEmptyEntryNoError),
      ("testCommitEntryFilePaths", testCommitEntryFilePaths),
      ("testCommitTestFixturePathEmptyEntryNoError", testCommitTestFixturePathEmptyEntryNoError),
      ("testCommitTestFixturePathNotEmptyEntryNoError", testCommitTestFixturePathNotEmptyEntryNoError)
    ]
  }

  extension LogEntryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogEntryTests = [
      ("testDefaultPathEmptyLogEntry", testDefaultPathEmptyLogEntry),
      ("testTestFixturePathNotEmptyEntryNoError", testTestFixturePathNotEmptyEntryNoError),
      ("testTestFixturePathNotEmptyEntryNoErrorMarkdown", testTestFixturePathNotEmptyEntryNoErrorMarkdown)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(ChangelogTests.__allTests__ChangelogTests),
      testCase(CommitEntryTests.__allTests__CommitEntryTests),
      testCase(LogEntryTests.__allTests__LogEntryTests)
    ]
  }
#endif
